/*
	###########################################################
	BLOQUE DE COMPROBACIONES INICIALES
	
	SI EXISTEN LAS TABLAS, LAS BORRO
	###########################################################
*/

-- BORRAR TABLA RESERVAS_DE_SERVICIOS SI EXISTE--
IF EXISTS
	(
		SELECT TABLE_NAME
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = UPPER('RESERVAS_DE_SERVICIOS')
		AND TABLE_SCHEMA = UPPER('DBO')
	)	
	DROP TABLE RESERVAS_DE_SERVICIOS;
GO

-- BORRAR TABLA TIPOS_DE_SERVICIOS SI EXISTE--
IF EXISTS
	(
		SELECT TABLE_NAME
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = UPPER('TIPOS_DE_SERVICIOS')
		AND TABLE_SCHEMA = UPPER('DBO')
	)	
	DROP TABLE TIPOS_DE_SERVICIOS;
GO

-- BORRAR TABLA RESERVAS_DE_HABITACIONES SI EXISTE--
IF EXISTS
	(
		SELECT TABLE_NAME
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = UPPER('RESERVAS_DE_HABITACIONES')
		AND TABLE_SCHEMA = UPPER('DBO')
	)	
	DROP TABLE RESERVAS_DE_HABITACIONES;
GO

-- BORRAR TABLA CLIENTES SI EXISTE--
IF EXISTS
	(
		SELECT TABLE_NAME
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = UPPER('CLIENTES')
		AND TABLE_SCHEMA = UPPER('DBO')
	)	
	DROP TABLE CLIENTES;
GO

-- BORRAR TABLA HABITACIONES SI EXISTE--
IF EXISTS
	(
		SELECT TABLE_NAME
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = UPPER('HABITACIONES')
		AND TABLE_SCHEMA = UPPER('DBO')
	)	
	DROP TABLE HABITACIONES;
GO

-- BORRAR TABLA TIPOS_DE_HABITACIONES SI EXISTE--
IF EXISTS
	(
		SELECT TABLE_NAME
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = UPPER('TIPOS_DE_HABITACIONES')
		AND TABLE_SCHEMA = UPPER('DBO')
	)	
	DROP TABLE TIPOS_DE_HABITACIONES;
GO

-- BORRAR TABLA TIPOS_DE_CAMAS SI EXISTE--
IF EXISTS
	(
		SELECT TABLE_NAME
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = UPPER('TIPOS_DE_CAMAS')
		AND TABLE_SCHEMA = UPPER('DBO')
	)	
	DROP TABLE TIPOS_DE_CAMAS;
GO

-- BORRAR TABLA USUARIOS SI EXISTE--
IF EXISTS
	(
		SELECT TABLE_NAME
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = UPPER('USUARIOS')
		AND TABLE_SCHEMA = UPPER('DBO')
	)	
	DROP TABLE USUARIOS;
GO

DROP VIEW IF EXISTS VIEW_DATOS_DE_HABITACIONES_DISPONIBLES;
DROP VIEW IF EXISTS dbo.VIEW_DATOS_DE_HABITACIONES_DISPONIBLES;
DROP VIEW IF EXISTS DATOS_DE_HABITACIONES_DISPONIBLES;
DROP VIEW IF EXISTS dbo.DATOS_DE_HABITACIONES_DISPONIBLES;

/*
	###########################################################
	FIN BLOQUE COMPROBACIONES
	###########################################################
*/
