--SELECT * FROM TIPOS_DE_CAMAS;
--SELECT * FROM TIPOS_DE_HABITACIONES;
--SELECT * FROM HABITACIONES;
--SELECT * FROM CLIENTES;
--SELECT * FROM RESERVAS_DE_HABITACIONES;
--SELECT * FROM TIPOS_DE_SERVICIOS;
--SELECT * FROM RESERVAS_DE_SERVICIOS;
--SELECT * FROM USUARIOS;

/*
-- no borrar por ahora hasta que la API se trague valores null
insert into usuarios (USERNAME, EMAIL, DNI, NOMBRE, APELLIDOS, PASS, ADMINISTRADOR, USUARIO_ACTIVO) 
values('elpepe', 'el@pepe.dick', '98981266A', 'el', 'pepe', 'elpepeelpepeelpepe', 1, 1);
*/

-- Obtener qué habitaciones, y de qué tipo, hay disponibles entre 2 fechas variables
DECLARE @FECHA_INICIO_RESERVA DATE = '16/07/2024'
DECLARE @FECHA_FIN_RESERVA DATE = '06/08/2024'

SELECT	*
FROM	HABITACIONES
WHERE	ID_HABITACION NOT IN 
(
    -- SELECT DE LAS HABITACIONES NO DISPONIBLES
    SELECT	
            R.ID_HABITACION
    FROM	RESERVAS_DE_HABITACIONES R
    WHERE	(FECHA_INICIO <= @FECHA_INICIO_RESERVA AND FECHA_FIN >= @FECHA_INICIO_RESERVA)
    OR		(FECHA_INICIO <= @FECHA_FIN_RESERVA AND FECHA_FIN >= @FECHA_FIN_RESERVA)
);
