--TIPOS, Y CANTIDAD DE HABITACIONES DISPONIBLES ENTRE FECHA1 Y FECHA2

--SELECT * FROM TIPOS_DE_HABITACIONES

DECLARE @FECHA_INICIO_RESERVA DATE = '2024-06-02';
DECLARE @FECHA_FIN_RESERVA DATE = '2024-06-04';

SELECT
	H.ID_TIPO_DE_HABITACION, 
	count(H.ID_TIPO_DE_HABITACION) "CANTIDAD DE HABITACIONES DISPONIBLES",
	T.CATEGORIA,
	T.PRECIO,
	T.DESCRIPCION,
	T.IMG_HABITACION_BASE_64,
	T.TAMAÑO,
	T.ENLACE_URL

FROM
	HABITACIONES H
	, TIPOS_DE_HABITACIONES T
WHERE
	ID_HABITACION IN 
	(1, 2, 9, 18, 20)
	AND H.ID_TIPO_DE_HABITACION = T.ID_TIPO_DE_HABITACION
group by 
	H.ID_TIPO_DE_HABITACION,
	T.CATEGORIA,
	T.PRECIO,
	T.DESCRIPCION,
	T.IMG_HABITACION_BASE_64,
	T.TAMAÑO,
	T.ENLACE_URL
;

