
DECLARE @FECHA_INICIO DATE = '2023-06-21';
DECLARE @FECHA_FIN DATE = '2023-06-27';

SELECT
	H.ID_TIPO_DE_HABITACION,
	COUNT(ID_HABITACION) as "CANTIDAD DISPONIBLE",
	T.CATEGORIA,
	T.PRECIO,
	T.DESCRIPCION,
	T.IMG_HABITACION_BASE_64,
	T.TAMAÑO,
	T.ENLACE_URL
FROM
	HABITACIONES H 
	LEFT JOIN TIPOS_DE_HABITACIONES T 
	ON H.ID_TIPO_DE_HABITACION = T.ID_TIPO_DE_HABITACION
WHERE
	ID_HABITACION NOT IN 
	(
		SELECT ID_HABITACION 
		FROM RESERVAS_DE_HABITACIONES
		WHERE
				@FECHA_FIN < FECHA_INICIO
			OR	@FECHA_INICIO > FECHA_FIN
			AND @FECHA_INICIO < @FECHA_FIN
	)
	AND
		@FECHA_INICIO < @FECHA_FIN

GROUP BY
	H.ID_TIPO_DE_HABITACION,
	T.CATEGORIA,
	T.PRECIO,
	T.DESCRIPCION,
	T.IMG_HABITACION_BASE_64,
	T.TAMAÑO,
	T.ENLACE_URL
;

