--TIPOS, Y CANTIDAD DE HABITACIONES DISPONIBLES ENTRE FECHA1 Y FECHA2

--SELECT * FROM TIPOS_DE_HABITACIONES

DECLARE @FECHA_INICIO_RESERVA DATE = '2024-06-02';
DECLARE @FECHA_FIN_RESERVA DATE = '2024-06-04';

SELECT
	ID_TIPO_DE_HABITACION, 
	count(ID_TIPO_DE_HABITACION) "CANTIDAD DE HABITACIONES DISPONIBLES"
FROM
	HABITACIONES
WHERE
	ID_HABITACION IN 
	(
		SELECT ID_HABITACION FROM RESERVAS_DE_HABITACIONES
		WHERE ID_HABITACION NOT IN 
		(
			SELECT	
				ID_HABITACION
			FROM
				RESERVAS_DE_HABITACIONES R
			WHERE
				FECHA_INICIO <= @FECHA_INICIO_RESERVA AND FECHA_FIN >= @FECHA_INICIO_RESERVA
		)
	)
group by 
	ID_TIPO_DE_HABITACION
;

